import { useState } from 'react';
import { Controller } from 'react-hook-form';
import { z } from 'zod';
import { Switch, View } from 'react-native';
import { api } from '@/lib/api/client';
import { Card } from '@/components/ui/card';
import { Text } from '@/components/ui/text';
import { Tabs } from '@/components/ui/tabs';
import { Select } from '@/components/ui/select';
import { FeatureForm } from '@/components/ui/feature-form';
const metricLabels = ['Haftalık çalışma saati','Devam zorunluluğu (%)','Proje yoğunluğu (%)','Sınav yoğunluğu (%)','İngilizce kullanım oranı','Grup çalışması oranı','Kampüste geçirilen saat','Aylık barınma maliyeti','Aylık ulaşım maliyeti','Aylık yemek maliyeti'];
const metricKeys = ['WEEKLY_STUDY_HOURS','ATTENDANCE_LEVEL','PROJECT_INTENSITY','EXAM_INTENSITY','ENGLISH_PERCENT','GROUP_WORK_PERCENT','CAMPUS_HOURS','MONTHLY_HOUSING_COST','MONTHLY_TRANSPORT_COST','MONTHLY_FOOD_COST'];
const metricSchema=z.object({metricKey:z.string().min(1),value:z.string().refine(value => value.trim()!=='' && Number.isFinite(Number(value)) && Number(value)>=0 && Number(value)<=1000000,'0–1.000.000 arasında bir değer gir.')});
const experienceSchema=z.object({templateType:z.string(),sentiment:z.enum(['NEUTRAL','POSITIVE','NEGATIVE']),title:z.string().trim().min(10).max(200),body:z.string().trim().min(20).max(5000)});
const careerSchema=z.object({sector:z.string().trim().min(2).max(120),firstRole:z.string().trim().min(2).max(120),companyType:z.string().trim().min(2).max(80),jobSearchMonths:z.string().regex(/^\d+$/).refine(value => Number(value)<=120),graduateStudy:z.boolean()});
const pollSchema=z.object({question:z.string().trim().min(10).max(300),options:z.string().refine(value => { const rows=value.split(/\n/).map(item=>item.trim()).filter(Boolean);return rows.length>=2 && rows.length<=10 && rows.every(item=>item.length<=120); },'Her satıra bir seçenek yaz: 2–10 seçenek, her biri en fazla 120 karakter.'),verifiedOnly:z.boolean()});
export function ContextContribution({universityId,programId,after}: {universityId:string;programId?:string;after:()=>void}) {
  const [tab,setTab]=useState('metric');
  return <Card><Text variant="heading">Deneyiminle katkı yap</Text><Tabs label="Katkı türü" value={tab} onChange={setTab} options={[{value:'metric',label:'Gerçek hayat ölçümü'},{value:'experience',label:'Deneyim'},...(programId?[{value:'career',label:'Kariyer yolculuğu'}]:[])]} />
    {tab==='metric' ? <FeatureForm schema={metricSchema} defaults={{metricKey:metricKeys[0],value:''}} fields={[{name:'value',label:'Değer',numeric:true}]} submit={values=>api.call('put','/api/context-metrics',{body:{universityId,programId,metricKey:values.metricKey,value:Number(values.value)},authenticated:true})} onSuccess={after}>{form=><Controller control={form.control} name="metricKey" render={({field})=><Select label="Ölçüm" value={field.value} onChange={field.onChange} options={metricKeys.map((value,index)=>({value,label:metricLabels[index]}))} />} />}</FeatureForm>
    : tab==='experience' ? <FeatureForm schema={experienceSchema} defaults={{templateType:'WHY_I_CHOSE',sentiment:'NEUTRAL',title:'',body:''}} fields={[{name:'title',label:'Başlık'},{name:'body',label:'Deneyim',multiline:true}]} label="Yayınla" submit={values=>api.call('post','/api/experiences',{body:{universityId,programId,...values},authenticated:true})} onSuccess={after}>{form=><><Controller control={form.control} name="templateType" render={({field})=><Select label="Şablon" value={field.value} onChange={field.onChange} options={[{value:'WHY_I_CHOSE',label:'Ben neden burayı seçtim?'},{value:'WISH_I_KNEW',label:'Keşke tercih etmeden önce bilseydim'},{value:'EXPECTATION_REALITY',label:'Beklediğim / gerçekte olan'},{value:'CHOOSE_AGAIN',label:'Tekrar tercih eder miydim?'}]} />} /><Controller control={form.control} name="sentiment" render={({field})=><Select label="Görüş yönü" value={field.value} onChange={field.onChange} options={[{value:'NEUTRAL',label:'Bilgilendirici'},{value:'POSITIVE',label:'Sevdiğim bir yön'},{value:'NEGATIVE',label:'Geliştirilmesi gereken yön'}]} />} /></>}</FeatureForm>
    : programId && <FeatureForm schema={careerSchema} defaults={{sector:'',firstRole:'',companyType:'',jobSearchMonths:'',graduateStudy:false}} fields={[{name:'sector',label:'Sektör'},{name:'firstRole',label:'İlk rol'},{name:'companyType',label:'Şirket türü'},{name:'jobSearchMonths',label:'İş bulma süresi (ay)',numeric:true}]} label="Anonim katkı yap" submit={values=>api.call('put','/api/career-outcomes',{body:{universityId,programId,...values,jobSearchMonths:Number(values.jobSearchMonths)},authenticated:true})} onSuccess={after}>{form=><Controller control={form.control} name="graduateStudy" render={({field})=><View className="flex-row items-center gap-2"><Text className="min-w-0 flex-1">Yüksek lisans yaptım/yapıyorum</Text><Switch accessibilityLabel="Yüksek lisans yaptım/yapıyorum" value={field.value} onValueChange={field.onChange} /></View>} />}</FeatureForm>}
  </Card>;
}
export function PollCreate({universityId,programId,after}: {universityId:string;programId?:string;after:()=>void}) {
  return <Card><Text variant="heading">Anket oluştur</Text><FeatureForm schema={pollSchema} defaults={{question:'',options:'',verifiedOnly:false}} fields={[{name:'question',label:'Soru'},{name:'options',label:'Seçenekler (her satıra bir seçenek)',multiline:true}]} label="Anketi yayınla" submit={values=>api.call('post','/api/polls',{body:{universityId,programId,question:values.question,options:values.options.split(/\n/).map(item=>item.trim()).filter(Boolean),verifiedOnly:values.verifiedOnly},authenticated:true})} onSuccess={after}>{form=><Controller control={form.control} name="verifiedOnly" render={({field})=><View className="flex-row items-center gap-2"><Text className="min-w-0 flex-1">Yalnız doğrulanmış öğrenci ve mezunlar oy versin</Text><Switch accessibilityLabel="Yalnız doğrulanmış katılım" value={field.value} onValueChange={field.onChange} /></View>} />}</FeatureForm></Card>;
}
