/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{ts,tsx}'],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        primary: '#163F36',
        'primary-strong': '#245449',
        'primary-soft': '#EDF2E8',
        'primary-foreground': '#FFFFFF',
        page: '#F8F7F1',
        surface: '#FFFFFF',
        text: '#21372F',
        muted: '#626D63',
        border: '#DEDFD3',
        candidate: '#3F83C5',
        student: '#35965D',
        graduate: '#C8102E',
        'candidate-soft': '#EEF6FD',
        'student-soft': '#EFF7F1',
        'graduate-soft': '#FFF1F3',
        'account-summary': '#F8FAF7',
        gold: '#D4AF37',
        'scope-general': '#FFF7C7',
        'scope-general-text': '#795B00',
        'scope-university': '#F2EBFC',
        'scope-university-text': '#65419A',
        'scope-program': '#FFF0DF',
        'scope-program-text': '#A64E08',
        danger: '#B42318',
        'danger-soft': '#FFF0F0',
        'danger-text': '#B6343E',
        'danger-border': '#E7B5B8',
        'secondary-border': '#B9C7BE',
        overlay: '#10251F',
        success: '#067647',
        warning: '#B54708',
      },
      spacing: { gutter: '14px', 'page-top': '24px', 'card-inset': '14px', 'list-gap': '10px', 'control-compact': '36px', 'control-large': '42px', 'touch-ios': '44px', 'touch-android': '48px', 'help-icon': '28px', 'header-height': '60px', 'dialog-x': '15px', 'dialog-y': '17px' },
      fontSize: {
        body: ['14px', { lineHeight: '23px' }],
        'page-title': ['26px', { lineHeight: '32px', letterSpacing: '-0.8px' }],
        'card-title': ['16px', { lineHeight: '22px', letterSpacing: '-0.3px' }],
        caption: ['12px', { lineHeight: '18px' }],
        metadata: ['11px', { lineHeight: '16px' }],
        excerpt: ['13px', { lineHeight: '20px' }],
        'dialog-title': ['18px', { lineHeight: '22px' }],
      },
      maxWidth: { dialog: '360px' },
      borderRadius: { control: '8px', card: '12px', surface: '16px', dialog: '13px' },
    },
  },
  plugins: [],
};
