/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{ts,tsx}'],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        primary: 'var(--color-primary)',
        'brand-accent': '#788A4E',
        'filter-field': '#FBFCFA',
        'primary-strong': '#245449',
        'primary-soft': 'var(--color-primary-soft)',
        'primary-foreground': '#FFFFFF',
        page: 'var(--color-page)',
        surface: '#FFFFFF',
        text: 'var(--color-text)',
        muted: 'var(--color-muted)',
        border: 'var(--color-border)',
        'about-art': '#E9ECDD', 'manager-page': '#F4F5F9', 'manager-border': '#E0E3EC', 'manager-text': '#202638', 'manager-muted': '#50546A', 'manager-primary': '#6A499E', 'manager-soft': '#F3ECFA', 'manager-heading': '#28234B',
        candidate: '#3F83C5',
        student: '#35965D',
        'profile-student': '#2F8F57',
        graduate: '#C8102E',
        'candidate-soft': '#EEF6FD',
        'student-soft': '#EFF7F1',
        'graduate-soft': '#FFF1F3',
        'account-summary': '#F8FAF7',
        'tab-track': '#EEF1EC',
        'tab-border': '#D9DED8',
        'notification-unread': '#FBFDF9',
        'notification-border': '#DCE3DD',
        'notification-unread-border': '#A8C8B7',
        'notification-indicator': '#2F8F57',
        gold: '#D4AF37', 'avatar-halo': '#F8EDC455', 'member': '#64748B',
        'rank-first': '#F5E6A8', 'rank-first-text': '#6F5811',
        'rank-second': '#E5E7E7', 'rank-second-text': '#596363',
        'rank-third': '#EDD2B7', 'rank-third-text': '#75502E',
        'rank-default': '#EEF1E9', 'rank-default-text': '#5F6D65',
        'scope-general': '#FFF7C7',
        'scope-general-text': '#795B00',
        'scope-university': '#F2EBFC',
        'scope-university-text': '#65419A',
        'scope-program': '#FFF0DF',
        'scope-program-text': '#A64E08',
        danger: '#B42318',
        'danger-soft': '#FFF0F0',
        'danger-text': '#B6343E',
        'danger-border': '#E7B5B8',
        'secondary-border': 'var(--color-secondary-border)',
        overlay: '#10251F',
        success: '#067647',
        warning: '#B54708',
      },
      spacing: { 'control-small': '28px', 'avatar-badge': '16px', 'avatar-badge-admin': '18px', 'avatar-badge-profile': '17px', 'avatar-badge-account': '20px', 'avatar-badge-ranking': '14px', 'avatar-badge-small-height': '30px', 'avatar-badge-admin-height': '38px', 'avatar-badge-profile-height': '32px', 'avatar-badge-account-height': '39px', 'avatar-badge-ranking-height': '27px', 'about-art': '260px', 'table-column': '120px', chart: '180px', 'avatar-question': '30px', 'avatar-ranking': '42px', 'avatar-star': '7px', gutter: '14px', 'page-top': '18px', 'card-inset': '12px', 'list-gap': '10px', 'control-compact': '36px', 'control-standard': '40px', 'control-large': '42px', 'touch-ios': '44px', 'touch-android': '48px', 'help-icon': '28px', 'header-height': '60px', 'dialog-x': '15px', 'dialog-y': '14px', 'select-list': '280px', 'account-inset': '14px' },
      fontSize: {
        'avatar-star': ['6px', { lineHeight: '6px' }],
        'avatar-star-admin': ['7px', { lineHeight: '7px' }],
        'avatar-star-account': ['8px', { lineHeight: '8px' }],
        'avatar-star-ranking': ['5px', { lineHeight: '5px' }],
        body: ['13px', { lineHeight: '21px' }],
        'page-title': ['24px', { lineHeight: '30px', letterSpacing: '-0.8px' }],
        'card-title': ['15px', { lineHeight: '21px', letterSpacing: '-0.3px' }],
        caption: ['12px', { lineHeight: '18px' }],
        metadata: ['11px', { lineHeight: '16px' }],
        palette: ['9px', { lineHeight: '12px' }],
        'compact-badge': ['10px', { lineHeight: '14px' }],
        'brand-small': ['16px', { lineHeight: '22px', letterSpacing: '-0.6px' }],
        'brand-word': ['20px', { lineHeight: '26px', letterSpacing: '-0.8px' }],
        excerpt: ['13px', { lineHeight: '20px' }],
        'dialog-title': ['18px', { lineHeight: '22px' }],
        'hero-title': ['30px', { lineHeight: '34px', letterSpacing: '-1px' }],
        metric: ['24px', { lineHeight: '30px' }],
        'account-name': ['19px', { lineHeight: '25px' }],
      },
      width: { 'metric-half': '48%' },
      minWidth: { brand: '134px' },
      maxWidth: { menu: '280px', dialog: '360px', content: '600px', 'header-account': '155px' },
      borderRadius: { 'about-art': '180px', control: '8px', card: '12px', surface: '16px', dialog: '13px' },
    },
  },
  plugins: [],
};
