/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{ts,tsx}'],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        primary: 'var(--color-primary)',
        'primary-strong': '#245449',
        'primary-soft': 'var(--color-primary-soft)',
        'primary-foreground': '#FFFFFF',
        page: 'var(--color-page)',
        surface: '#FFFFFF',
        text: 'var(--color-text)',
        muted: 'var(--color-muted)',
        border: 'var(--color-border)',
        'about-art': '#E9ECDD', 'manager-page': '#F4F5F9', 'manager-border': '#E0E3EC', 'manager-text': '#202638', 'manager-muted': '#50546A', 'manager-primary': '#6A499E', 'manager-soft': '#F3ECFA', 'manager-heading': '#28234B',
        candidate: '#3F83C5',
        student: '#35965D',
        graduate: '#C8102E',
        'candidate-soft': '#EEF6FD',
        'student-soft': '#EFF7F1',
        'graduate-soft': '#FFF1F3',
        'account-summary': '#F8FAF7',
        'tab-track': '#EEF1EC',
        'tab-border': '#D9DED8',
        'notification-unread': '#FBFDF9',
        'notification-border': '#DCE3DD',
        'notification-unread-border': '#A8C8B7',
        'notification-indicator': '#2F8F57',
        gold: '#D4AF37',
        'scope-general': '#FFF7C7',
        'scope-general-text': '#795B00',
        'scope-university': '#F2EBFC',
        'scope-university-text': '#65419A',
        'scope-program': '#FFF0DF',
        'scope-program-text': '#A64E08',
        danger: '#B42318',
        'danger-soft': '#FFF0F0',
        'danger-text': '#B6343E',
        'danger-border': '#E7B5B8',
        'secondary-border': 'var(--color-secondary-border)',
        overlay: '#10251F',
        success: '#067647',
        warning: '#B54708',
      },
      spacing: { 'about-art': '260px', 'table-column': '120px', chart: '180px', 'avatar-question': '30px', 'avatar-star': '7px', gutter: '14px', 'page-top': '24px', 'card-inset': '14px', 'list-gap': '10px', 'control-compact': '36px', 'control-standard': '40px', 'control-large': '42px', 'touch-ios': '44px', 'touch-android': '48px', 'help-icon': '28px', 'header-height': '60px', 'dialog-x': '15px', 'dialog-y': '17px', 'select-list': '280px', 'account-inset': '18px' },
      fontSize: {
        'avatar-star': ['7px', { lineHeight: '8px' }],
        body: ['14px', { lineHeight: '23px' }],
        'page-title': ['26px', { lineHeight: '32px', letterSpacing: '-0.8px' }],
        'card-title': ['16px', { lineHeight: '22px', letterSpacing: '-0.3px' }],
        caption: ['12px', { lineHeight: '18px' }],
        metadata: ['11px', { lineHeight: '16px' }],
        excerpt: ['13px', { lineHeight: '20px' }],
        'dialog-title': ['18px', { lineHeight: '22px' }],
        'hero-title': ['30px', { lineHeight: '34px', letterSpacing: '-1px' }],
        metric: ['24px', { lineHeight: '30px' }],
        'account-name': ['19px', { lineHeight: '25px' }],
      },
      width: { 'metric-half': '48%' },
      maxWidth: { dialog: '360px', content: '600px', 'header-account': '155px' },
      borderRadius: { 'about-art': '180px', control: '8px', card: '12px', surface: '16px', dialog: '13px' },
    },
  },
  plugins: [],
};
